import type { CSSProperties } from "react";
import {
  BarChart3,
  Book,
  Briefcase,
  Building2,
  CalendarDays,
  Camera,
  Code,
  Coffee,
  Compass,
  Dumbbell,
  Flame,
  FlaskConical,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  MapPin,
  Music,
  Palette,
  Pencil,
  Plane,
  type LucideIcon,
  Rocket,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  Trophy,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  Zap,
} from "lucide-react";

const iconByKey: Record<string, LucideIcon> = {
  book: Book,
  briefcase: Briefcase,
  building: Building2,
  calendar: CalendarDays,
  camera: Camera,
  cart: ShoppingCart,
  chart: BarChart3,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  dashboard: LayoutDashboard,
  dumbbell: Dumbbell,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  graduation: GraduationCap,
  heart: Heart,
  home: Home,
  invitations: UserPlus,
  labs: FlaskConical,
  lightbulb: Lightbulb,
  map: MapPin,
  music: Music,
  organics: Leaf,
  palette: Palette,
  pencil: Pencil,
  personal: UserRound,
  plane: Plane,
  rocket: Rocket,
  shield: Shield,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trending: TrendingUp,
  trophy: Trophy,
  users: Users,
  wallet: Wallet,
  zap: Zap,
};

export function BoardIcon({
  className,
  iconKey,
  style,
}: {
  className?: string;
  iconKey: string;
  style?: CSSProperties;
}) {
  const Icon = iconByKey[iconKey] ?? LayoutDashboard;

  return <Icon className={className} strokeWidth={2.1} style={style} />;
}
